for large model size netron is very usefull to  study about the model

In [ ]:
#tf.constant,tf.variable,tf.placeholder,tf.zeros,tf.truncated_normal,tf.random_normal,linear equation,feed_dict,cost function etc.,

In [4]:
!pip install tensorflow==1.14

ERROR: Could not find a version that satisfies the requirement tensorflow==1.14 (from versions: 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.10.1, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0, 2.11.1, 2.12.0rc0, 2.12.0rc1, 2.12.0, 2.12.1, 2.13.0rc0, 2.13.0rc1, 2.13.0rc2, 2.13.0, 2.13.1, 2.14.0rc0, 2.14.0rc1, 2.14.0, 2.14.1, 2.15.0rc0, 2.15.0rc1, 2.15.0, 2.15.1, 2.16.0rc0, 2.16.1, 2.16.2, 2.17.0rc0, 2.17.0rc1, 2.17.0, 2.17.1, 2.18.0rc0, 2.18.0rc1, 2.18.0rc2, 2.18.0, 2.18.1, 2.19.0rc0, 2.19.0, 2.19.1, 2.20.0rc0, 2.20.0)
ERROR: No matching distribution found for tensorflow==1.14


In [2]:
import tensorflow as tf


In [3]:
tf.__version__

'2.14.0'

In [4]:
hello_constant=tf.constant('hello world!')
hello_constant

<tf.Tensor: shape=(), dtype=string, numpy=b'hello world!'>

In [5]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

hello_constant = tf.constant("hello world!")

with tf.Session() as sess:
    output = sess.run(hello_constant)
    print(output.decode("utf-8"))

Instructions for updating:
non-resource variables are not supported in the long term
hello world!


In [6]:
#create tensorflow object called tensor
hello_constant=tf.constant('hello world!')
with tf.Session() as sess:
    #run the tf.constant operation in the session
    output=sess.run(hello_constant)
    print(output)

b'hello world!'


this error is because you are mixing TensorFlow 1.x style code with TensorFlow 2.x.

In TF1, we used:

with tf.Session() as sess:
    output = sess.run(hello_constant)


In TF2, eager execution is enabled by default — meaning tensors run immediately, no session is needed.

So your code should be:

import tensorflow as tf

# create a tensor object
hello_constant = tf.constant("hello world!")

# no session needed in TF2
print(hello_constant.numpy().decode("utf-8"))


✅ Output:

hello world!


⚡ Options for you:

Stay with TF2 (recommended) → write code without Session().

Use TF1 compatibility mode if you want old-style code:

import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

hello_constant = tf.constant("hello world!")

with tf.Session() as sess:
    output = sess.run(hello_constant)
    print(output.decode("utf-8"))


Key facts:

TF 1.14 only works with Python 3.6 (sometimes 3.7).

You’re probably on Python 3.9+ (since you see TF 2.8+ available).

That’s why pip can’t find tensorflow==1.14 for your setup.

✅ You have 3 choices:

Option 1 (Recommended): Use TF2 code

Convert your TF1-style code (Session(), placeholder, etc.) to TF2 eager mode.
Example conversion I showed earlier:

import tensorflow as tf

hello_constant = tf.constant("hello world!")
print(hello_constant.numpy().decode("utf-8"))

Option 2: Run TF1.14 in a compatible environment

If you really need TensorFlow 1.14, you must:

Create a new conda env with Python 3.6:

conda create -n tf1 python=3.6
conda activate tf1


Install TF1.14:

pip install tensorflow==1.14

Option 3: Use TF1 compatibility mode inside TF2

If you don’t want to downgrade Python, just run TF1-style code in TF2:

import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

hello_constant = tf.constant("hello world!")

with tf.Session() as sess:
    output = sess.run(hello_constant)
    print(output.decode("utf-8"))

data is stored as object called tensor,edge or data

In [7]:
# A is a 0-dimensional int32 tensor
A = tf.constant(1234)

# B is a 1-dimensional int32 tensor
B = tf.constant([123,456,789])

# C is a 2-dimensional int32 tensor
C = tf.constant([[123,456,789],[222,333,444]])


In [9]:
with tf.Graph().as_default():
    c1 = tf.constant(4, dtype=tf.float64, name="c")
    c2 = tf.constant(4, dtype=tf.int32, name="c")
    c3 = tf.constant(4, dtype=tf.int32, name="c")
    print(c1.name)
    print(c2.name)
    print(c3.name)

c:0
c_1:0
c_2:0


In [10]:
with tf.Graph().as_default():
    c1 = tf.constant(4, dtype=tf.float64, name='c')
    with tf.name_scope("prefix_name"):
        c2 = tf.constant(4, dtype=tf.int32, name='c')
        c3 = tf.constant(4, dtype=tf.float64, name='c')
    print(c1.name)
    print(c2.name)
    print(c3.name)
    print(c1)


c:0
prefix_name/c:0
prefix_name/c_1:0
Tensor("c:0", shape=(), dtype=float64)


In [11]:
C = tf.constant([[123,456,789], [222,333,444]])
sess = tf.Session()
sess.run(C)


array([[123, 456, 789],
       [222, 333, 444]])

In TensorFlow 1.x, when you create a tensor inside a with tf.Graph().as_default(): block, that tensor belongs only to that graph.

Later, when you open a plain tf.Session(), by default it attaches to the default graph, not the custom graph.

So your tensor (c1) doesn’t “belong” to that session’s graph, and TensorFlow raises this error.

✅ 3 Ways to Fix
Option 1: Keep everything in the same graph
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

g = tf.Graph()
with g.as_default():
    c1 = tf.constant(4.0, dtype=tf.float64, name="c")

with tf.Session(graph=g) as sess:
    print(sess.run(c1))

Option 2: Don’t use a custom graph

Just use the default graph:

import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

c1 = tf.constant(4.0, dtype=tf.float64, name="c")

with tf.Session() as sess:
    print(sess.run(c1))

In [16]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

g = tf.Graph()
with g.as_default():
    c1 = tf.constant(4.0, dtype=tf.float64, name="c")

with tf.Session(graph=g) as sess:
    print(sess.run(c1))


4.0


In [17]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

c1 = tf.constant(4.0, dtype=tf.float64, name="c")

with tf.Session() as sess:
    print(sess.run(c1))


4.0


In [18]:
init_val = tf.random_normal([1,5],0,1)
var = tf.Variable(init_val, name="var")
print("pre run: \n{}".format(var))
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    post_var = sess.run(var)
    print("\npost run \n{}".format(post_var))


pre run: 
<tf.Variable 'var:0' shape=(1, 5) dtype=float32_ref>

post run 
[[-0.8237677  -0.06258353 -2.0322533  -0.41873977 -0.22384034]]


In [19]:
init_val = tf.random_normal([1,5],0,1)
var = tf.Variable(init_val, name="var")
print("pre run: \n{}".format(var))
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    post_var = sess.run(var)
    print("\npost run \n{}".format(post_var))
#getting different values if run again

pre run: 
<tf.Variable 'var_1:0' shape=(1, 5) dtype=float32_ref>

post run 
[[ 0.44501194 -0.9604136  -0.04612495 -0.5894625   0.54562217]]


In [21]:
init_val = tf.random_normal([1,5],0,1)
var = tf.get_variable(init_val, name="var")
print("pre run: \n{}".format(var))
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    post_var = sess.run(var)
    print("\npost run \n{}".format(post_var))
#getting different values if run again
#create different input tensors and use get_variables()fn

TypeError: get_variable() got multiple values for argument 'name'

In [22]:
#tf.placeholder() and feed_dict()
x=tf.placeholder(tf.string)
with tf.Session() as sess:
    output=sess.run(x,feed_dict={x: 'test'})
    print(output)


test


In [23]:
x=tf.placeholder(tf.string)
with tf.Session() as sess:
    output=sess.run(x)#should give dictionary feed tensors necessarily
    print(output)

InvalidArgumentError: Graph execution error:

Detected at node 'Placeholder_1' defined at (most recent call last):
    File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\runpy.py", line 196, in _run_module_as_main
    File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\runpy.py", line 86, in _run_code
    File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\site-packages\ipykernel\kernelapp.py", line 739, in start
    File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\site-packages\tornado\platform\asyncio.py", line 211, in start
    File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\asyncio\base_events.py", line 603, in run_forever
    File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\asyncio\base_events.py", line 1909, in _run_once
    File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\asyncio\events.py", line 80, in _run
    File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\site-packages\ipykernel\kernelbase.py", line 545, in dispatch_queue
    File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\site-packages\ipykernel\kernelbase.py", line 534, in process_one
    File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\site-packages\ipykernel\kernelbase.py", line 437, in dispatch_shell
    File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\site-packages\ipykernel\ipkernel.py", line 362, in execute_request
    File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\site-packages\ipykernel\kernelbase.py", line 778, in execute_request
    File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\site-packages\ipykernel\ipkernel.py", line 449, in do_execute
    File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    File "C:\Users\Welcome\AppData\Local\Temp\ipykernel_1372\1459820489.py", line 1, in <module>
Node: 'Placeholder_1'
You must feed a value for placeholder tensor 'Placeholder_1' with dtype string
	 [[{{node Placeholder_1}}]]

Original stack trace for 'Placeholder_1':
  File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\runpy.py", line 196, in _run_module_as_main
  File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\runpy.py", line 86, in _run_code
  File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\site-packages\ipykernel_launcher.py", line 18, in <module>
  File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
  File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\site-packages\ipykernel\kernelapp.py", line 739, in start
  File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\site-packages\tornado\platform\asyncio.py", line 211, in start
  File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\asyncio\base_events.py", line 603, in run_forever
  File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\asyncio\base_events.py", line 1909, in _run_once
  File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\asyncio\events.py", line 80, in _run
  File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\site-packages\ipykernel\kernelbase.py", line 545, in dispatch_queue
  File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\site-packages\ipykernel\kernelbase.py", line 534, in process_one
  File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\site-packages\ipykernel\kernelbase.py", line 437, in dispatch_shell
  File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\site-packages\ipykernel\ipkernel.py", line 362, in execute_request
  File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\site-packages\ipykernel\kernelbase.py", line 778, in execute_request
  File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\site-packages\ipykernel\ipkernel.py", line 449, in do_execute
  File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
  File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
  File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
  File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
  File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
  File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
  File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
  File "C:\Users\Welcome\AppData\Local\Temp\ipykernel_1372\1459820489.py", line 1, in <module>
  File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\site-packages\tensorflow\python\ops\array_ops.py", line 3283, in placeholder
  File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 8843, in placeholder
  File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 796, in _apply_op_helper
  File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\site-packages\tensorflow\python\framework\ops.py", line 2657, in _create_op_internal
  File "C:\Users\Welcome\anaconda3\envs\mycorrectenv\lib\site-packages\tensorflow\python\framework\ops.py", line 1161, in from_node_def


In [25]:
x=tf.placeholder(tf.string)
y=tf.placeholder(tf.int32)
z=tf.placeholder(tf.float32)

with tf.Session() as sess:
    output_x=sess.run(x,feed_dict={x: 'Test String',  y:123,   z:45.67})
    output_y=sess.run(y,feed_dict={x: 'Test String',  y:123,   z:45.67})
    print(output_x)
    print(output_y)

Test String
123


In [27]:
'''A Session object encapsulates the environment in which Operation
objects are executed, and Tensor objects are evaluated. '''

# Build a graph.
a = tf.constant(5.0)
b = tf.constant(6.0)
c = a * b
c

<tf.Tensor 'mul:0' shape=() dtype=float32>

In [28]:
x = tf.placeholder("float", None)
y = x ** 2

with tf.Session() as session:
    result = session.run(y, feed_dict={x: [1., 2., 3.]})
    print(result)


'''Note: If the data passed to the feed dict doesn’t match the tensor type and
shape, it will raise an error.'''

[1. 4. 9.]


'Note: If the data passed to the feed dict doesn’t match the tensor type and\nshape, it will raise an error.'

In [29]:
x=tf.add(5,2)
with tf.Session() as sess:
    output=sess.run(x)
    print(output)

7


In [30]:
x=tf.subtract(10,4)
y=tf.multiply(2,5)

In [31]:
x
y

<tf.Tensor 'Mul_1:0' shape=() dtype=int32>

In [32]:
sess = tf.Session()
sess.run(x)

6

In [33]:
sess = tf.Session()
sess.run(y)

10

In [34]:
#if data types doesnt match it gives error
tf.subtract(tf.constant(2.0),tf.constant(1))

TypeError: Input 'y' of 'Sub' Op has type int32 that does not match type float32 of argument 'x'.

In [35]:
x=tf.constant(10)
y=tf.constant(2)
z=tf.subtract(tf.divide(x,y),1)

with tf.Session() as sess:
    output=sess.run(z)
    print(output)

4.0


#define linear equation function with tensorflow


In [36]:
#define linear equation function with tensorflow

n_features=120
n_labels=5

weights = tf.Variable(tf.truncated_normal([n_features, n_labels]))
weights

<tf.Variable 'Variable:0' shape=(120, 5) dtype=float32_ref>

In [38]:
n_labels=5

bias = tf.Variable(tf.zeros(n_labels))

using feed_dict

In [39]:
import tensorflow as tf

a = tf.constant(3)
b = tf.constant(4)
c = a * b

# Define placeholder
x = tf.placeholder(tf.float32)

# Replace value of a with x using feed_dict
with tf.Session() as session:
    result = session.run(c, feed_dict={a: x})
    print(result)


AttributeError: module 'tensorflow' has no attribute 'placeholder'

You're using TensorFlow 2.x, but the code in your notes is written for TensorFlow 1.x.

In TensorFlow 2.x:

tf.placeholder() and tf.Session() do not exist anymore because TF2 runs in eager execution mode by default.

feed_dict is also not used the same way.

🔧 How to Fix It

If you still want to use old TF1-style code in TF2, you must enable compatibility mode:

import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

a = tf.constant(3)
b = tf.constant(4)
c = a * b

# Define placeholder (works in compat mode)
x = tf.placeholder(tf.float32)

with tf.Session() as session:
    result = session.run(c, feed_dict={a: 5})
    print(result)

✅ Modern TensorFlow 2.x way (without placeholders/sessions)

In TF2, you would instead just use eager execution directly:

import tensorflow as tf

a = tf.constant(3)
b = tf.constant(4)
c = a * b

print(c.numpy())  # Output: 12


If you want the effect of placeholders, you use tf.function + function arguments:

import tensorflow as tf

@tf.function
def multiply(a, b):
    return a * b

print(multiply(3, 4).numpy())  # Output: 12

In [40]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

a = tf.constant(3)
b = tf.constant(4)
c = a * b

# Define placeholder (works in compat mode)
x = tf.placeholder(tf.float32)

with tf.Session() as session:
    result = session.run(c, feed_dict={a: 5})
    print(result)


20


In [43]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

# Define placeholder instead of constant so we can feed values
a = tf.placeholder(tf.int32)
b = tf.constant(4)

c = a * b

with tf.Session() as session:
    # First run: a = 3
    result1 = session.run(c, feed_dict={a: 3})
    print(result1)   # Output: 12

    # Second run: a = 5
    result2 = session.run(c, feed_dict={a: 5})
    print(result2)   # Output: 20


12
20


In [44]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

a = tf.constant(3)
b = tf.constant(4)
c = a * b

# Define placeholder (works in compat mode)
x = tf.placeholder(tf.float32)

with tf.Session() as session:
    result = session.run(c, feed_dict={a: 5})
    print(result)


20


In [46]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

# Define placeholders
a = tf.placeholder(tf.int32)
b = tf.constant(4)

c = a * b

with tf.Session() as session:
    result = session.run(c, feed_dict={a: 3})  # a = 3
    print(result)  # Output: 12


12


In [50]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()


a = tf.constant(3)
b = tf.constant(4)
c = a * b

# Define placeholder
x = tf.placeholder(tf.int32)

# Replace value of a with x using feed_dict
with tf.Session() as session:
    result = session.run(c, feed_dict={a: x})
    print(result)


TypeError: The value of a feed cannot be a tf.Tensor object. Acceptable feed values include Python scalars, strings, lists, numpy ndarrays, or TensorHandles. For reference, the tensor object was Tensor("Placeholder_13:0", dtype=int32) which was passed to the argument `feed_dict` with key Tensor("Const_29:0", shape=(), dtype=int32).

In [53]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

# Create Operations, Tensors, etc (using the default graph)
a = tf.add(2, 5)
b = tf.multiply(a, 3)

# Start up a 'Session' using the default graph
sess = tf.Session()

# Define a dictionary that says to replace the value of 'a' with 15
replace_dict = {a: 15}

# Run the session, passing in 'replace_dict' as the value to 'feed_dict'
output = sess.run(b, feed_dict=replace_dict)

print(output)


45


create Tensrflow softmax activation function using tensorflow

In [55]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()


def run_2():

    output = None
    logit_data = [19,354,354,45,354,54]
    logits = tf.placeholder(tf.float32)
    # Calculate the softmax of the logits
    softmax = tf.nn.softmax(logits)

    with tf.Session() as sess:
        # Feed in the logit data
        output = sess.run(softmax, feed_dict={logits: logit_data})
    return output

print(run_2())

[0.         0.33333334 0.33333334 0.         0.33333334 0.        ]


create cross entropy using loss function

In [56]:
#Cross-Entropy Code Example
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

softmax_data = [0.7, 0.2, 0.1]
one_hot_data = [1.0, 0.0, 0.0]

softmax = tf.placeholder(tf.float32)
one_hot = tf.placeholder(tf.float32)

# Print cross entropy from session
cross_entropy = -tf.reduce_sum(tf.multiply(one_hot, tf.log(softmax)))

with tf.Session() as session:
     output = session.run(cross_entropy, feed_dict={one_hot: one_hot_data, softmax: softmax_data})
     print(output)



0.35667497
